### ISSUE TITLE
Translation pt-br

### ISSUE THREAD

**Issue by jsds96** [rogeraabbccdd/CSGO-Emoji#1]
Add Brazilian Portuguese translation.

**Comment by jsds96** [comment]
> {
	"Not Found"
	{
		"#format"		"{1:s}"
		"en"			"{GREEN}[MVP] {RED} Emoji {PINK}{1} {RED}not found!"
		"zho"			"{GREEN}[MVP] {RED} 找不到表情符號 {PINK}{1} {RED}!"
		"pt"			"{GREEN}[MVP] {RED} Emoji {PINK}{1} {RED}não encontrado!"
	}
	"No Flag"
	{
		"#format"		""
		"en"			"{GREEN}[MVP] {RED}You don't have access to use this emoji."
		"zho"			"{GREEN}[MVP] {RED}你沒有使用這個表情符號的權限."
		"pt"			"{GREEN}[MVP] {RED}Você não tem acesso para usar este emoji."
	}
	"Displaying"
	{
		"#format"		"{1:s}"
		"en"			"{GREEN}[MVP] {LIGHTGREEN}Displaying emoji {PINK}{1}{LIGHTGREEN}."
		"zho"			"{GREEN}[MVP] {LIGHTGREEN}顯示表情符號 {PINK}{1}{LIGHTGREEN}."
		"pt"			"{GREEN}[MVP] {LIGHTGREEN}Exibindo emoji {PINK}{1}{LIGHTGREEN}."
	}
	"Menu Title"
	{
		"#format"		""
		"en"			"Select Emoji"
		"zho"			"選擇表情符號"
		"pt"			"Selecionar Emoji"
	}
}

**Comment by rogeraabbccdd** [comment]
Hi, you should create a new pull request, not an issue.
